### ISSUE TITLE
Yaml Code

### ISSUE THREAD

**Issue by FlyingEagle** [ntoff/OctoPrint-Estop#3]
Could you insert a valid yaml patch code for plugin yamlpatcher to your faq?

**Comment by ntoff** [comment]
I can look into it but as of right now I wouldn't know what to even put there, I've never used the yaml patcher plugin (I've installed it in the past but could never figure out how to actually get it to work).

Leave it with me and I'll see if I can figure it out.

**Comment by ntoff** [comment]
Since the yaml patcher doesn't seem to like the code required to put this plugin at the top, and this sidebar order plugin appears to exist https://github.com/zoombahh/OctoPrint-SidebarOrder I'm closing this issue as one that I believe to be impossible to solve using yaml patcher alone. Yaml patcher just refuses to accept the code block required to move the estop plugin to the top, at least as far as I can figure out.

If anyone else does figure it out, please let me know and I'll add it to the FAQ.
