### ISSUE TITLE
Automatic Reconnect after EStop

### ISSUE THREAD

**Issue by VibroAxe** [ntoff/OctoPrint-Estop#4]
Is there any way to get the octoprint / OctoPrint-Estop to automatically reconnect to the printer after the estop is recieved? I've read gina's comments on why octoprint itself doesn't usually reconnect after a serial failure but the estop situation is very specific. Also disconnecting and reconnecting usually ensures the arduino reset lines are toggled which improves the chances of ensuring everything actually stops/disables.

Thoughts?

**Comment by ntoff** [comment]
I couldn't say either way as I haven't looked into it. I can have a talk with @foosel and see whether she thinks it'd be a bad / good option and the best way to pull it off. Whether it might potentially cause issues.

I guess having it as an option that defaults to off could work, then users can enable it at their own risk. I agree having an auto re-connect does make more sense for an emergency stop button, since you're the one who pressed it so it's very likely you've already seen whatever error it is that caused you to press the button.

**Comment by ntoff** [comment]
Give this branch a try https://github.com/ntoff/OctoPrint-Estop/tree/reconnect 

mash the button, try to break it, print stuff, don't print stuff, move stuff, do all the things. All I have is the virtual printer to try it out on at the moment. I've made an option in the settings menu to "cycle the connection", it'll attempt to disconnect and then reconnect which could help break out of heatup commands and other so called "blocking" commands.

You'll have to manually install it with this url https://github.com/ntoff/OctoPrint-Estop/archive/reconnect.zip as it's not pushed out as an auto update yet. That's only if you want to help test it, if not then just wait until I've had a chance to test it on my real printers and an auto update.

**Comment by VibroAxe** [comment]
sorry for the delay after the incredibly fast response @ntoff i'll have a play today

**Comment by VibroAxe** [comment]
inital review this seems to work absolutely perfectly. I'll try a few more mid print aborts later, but looks like a nice solution

**Comment by VibroAxe** [comment]
Also works nicely in the case the printer fails to receive the estop M114 for any reason

**Comment by ntoff** [comment]
I just made it call octoprint's built in disconnect, then reconnect when it detects the offline state using OctoPrint's "events". 

The only issues I ran into were during heat up commands where OctoPrint takes a while to disconnect but I can't really control how OctoPrint's connection thing works or force it to disconnect faster.

**Comment by ntoff** [comment]
@VibroAxe I totally forgot about this request: https://github.com/foosel/OctoPrint/issues/2287 

I might wait and see what happens with that, see if any sort of confirmation dialog on disconnect interferes with anything. I don't want to put a disconnect thing into the e-stop plugin, and then when someone hits the e-stop button, a confirmation pops up.

**Comment by foosel** [comment]
That confirmation - if implemented - will be a frontend only thing. So if your plugin is simply reconnecting in python in the backend, it won't run into this.

**Comment by ntoff** [comment]
@foosel I'm not  using python https://github.com/ntoff/OctoPrint-Estop/commit/62a6dac6e963d39f89fd98f5e3008dcd88f0f5be#diff-6b50a04e242b6ae15d08a0259f0fddcbR55 It's done with javascript just calling for a disconnect().

**Comment by VibroAxe** [comment]
@ntoff Confirmation definitely calls the same disconnect method after it's confirmation, so this fix will still override the confirmation prompt (as it should do for an estop)

```javascript
+                        onproceed:  function() {
+                            OctoPrint.connection.disconnect();
+                        }
```

**Comment by VibroAxe** [comment]
I might have just worked out a bug, but i'm mid print and so can't test till later today/tomorrow

From looking at the code it LOOKS like once the estop button has been pressed any further manual disconnection would automatically be reconnected as the event handler is never removed.

I suspect line 57-59 (https://github.com/ntoff/OctoPrint-Estop/blob/reconnect/octoprint_estop/static/js/estop.js#L57) should become somthing more like
```javascript
self.onEventDisconnected =function () {     //wait until octoprint has disconnected
                        self.onEventDisconnected = null        //unregister event handler
                        OctoPrint.connection.connect();         //reconnect
}
```

**Comment by ntoff** [comment]
ok cool, I'll give it a go later on. I don't think I ever tried a manual disconnect so I'll check out what happens there too.

**Comment by VibroAxe** [comment]
Confirmed, as I thought, once you have estopped you can no longer disconnect from the serial port as it instantly reconnects!

**Comment by ntoff** [comment]
I added your suggestion and it seems to do the trick, thanks. Also doesn't seem to be affected by the new disconnection confirmation thingamajig.

I'm considering adding a small delay before reconnecting (just a couple of seconds), at the moment it's a bit quick and kind of hard to tell whether it's actually disconnected or not without staring at the terminal. I don't know how fast it happens on a raspberry pi or something lower powered (I'm testing on the virtual printer on a pretty fast PC) but the disconnect/reconnect is pretty much instantaneous for me.

**Comment by VibroAxe** [comment]
That would make sense, I did have one test last night which seemed to get a bit confused, I suspect because the serial reconnected before the printer had finished estopping or something

**Comment by ntoff** [comment]
It only calls the connect after it sees the printer is offline so I don't know, I'm not too well versed on how the serial connection stuff works.

edit: I've just had a go on my real printer, seems to function fairly  similar to the virtual tests. Do you remember exactly what you were doing that made it confused?

**Comment by ntoff** [comment]
@VibroAxe I've added a 3 second delay between detecting its offline, and reconnecting. I also made the button say "Reconnecting..." if it's set to reconnect.

I've also changed the way it works in regards to the offline event, setting it to null was leading to javascript console errors so I've just set it to always check for offline status, but now it'll only (or should only) do anything if the offline status comes after hitting the emergency stop button, just disconnecting *shouldn't* do anything (other than disconnect).

**Comment by VibroAxe** [comment]
@foosel whats the "proper" way to unregister an event handle for a js plugin?

**Comment by foosel** [comment]
Delete it from your view model (it gets called via a property check, so if it's not there anymore it won't get called). But personally I'd rather use an internal flag that tells me to ignore events there instead of registration cycles.

**Comment by ntoff** [comment]
https://github.com/ntoff/OctoPrint-Estop/blob/reconnect/octoprint_estop/static/js/estop.js#L62

@VibroAxe  I just told it to do nothing if it wasn't called from the emergency stop button (which I assume is what foosel means by ignoring events?)

**Comment by VibroAxe** [comment]
@foosel i'd definitely argue that in js you should check not only the property is present, but also !null before trying to call a function. But seems like @ntoff's solution is ok to get around this

**Comment by foosel** [comment]
@VibroAxe I agree. To be honest though, I so far never had anyone try setting the handler to null and as much as I try to, I can't think of everything beforehand ;)

**Comment by ntoff** [comment]
>as much as I try to, I can't think of everything beforehand

That's why you have me, I'm good at doing weird stuff that no one ever thinks of. Stuff like turning off a setting, pressing a button, then turning the setting back on, and pressing another button. Found a weird combination of events that no one would ever do that would lead to my "fix" not working, but that's fixed now :)

**Comment by VibroAxe** [comment]
My bad :P

I'm not massively used to javascripts loose property definitions, setting the handler to null seemed like an obvious choice

I suspect the code should probably have read
```javascript
delete self.onEventDisconnected        //unregister event handler
```

My personal though would be that removing the veent handler when it's not needed is more efficient and less likely to bite you by an error in the logic causing the handler to fire when it shouldn't. I'll leave that for @ntoff to decide though :P

**Comment by ntoff** [comment]
@VibroAxe I'm about as close to a javascript developer as a fly is to a rocket scientist. Sure they can both fly, but only one of them knows how/why.

I see javascript, I make the javascript do things, but I have no idea why or how it works. I'm totally open to suggestions, as long as the suggestion doesn't break my current implementation too much since.

If y'all'd like to test the current version of it in the reconnect branch https://github.com/ntoff/OctoPrint-Estop/tree/reconnect I've added a big scary warning and if there's no objections then I'll merge it with master and make it permanent.

**Comment by foosel** [comment]
^- there you go, it will now also be checked if a handler to call on a view model is actually a function (which `null` ain't).

**Comment by ntoff** [comment]
but wouldn't it still be "wrong" to just set it as a null? You said it'd be better to use a flag to just tell it to do nothing.

This is why I don't bother registering most of my plugins, as long as they work for me I can live with weird errors and inefficient java demons living in my pi. I have no idea what I'm doing

what's this button d

**Comment by foosel** [comment]
javascript* :P

And "wrong" is too strong a word. Personally I wouldn't set it to null because it honestly feels like if that's the solution to the problem maybe the problem should be rethought. But the code certainly shouldn't fall flat on its face when you DO set it to null, and that should now be ensured.

**Comment by ntoff** [comment]
well it's in there now, doing its own thing, constantly looking for a disconnection, and sitting idly by until its told otherwise. At least I hope it sits idly by, I hope it doesn't get together with that other sly function in an attempt to take over the world. 

I hope I haven't accidentally created skynet.

**Comment by ntoff** [comment]
https://github.com/ntoff/OctoPrint-Estop/tree/reconnect-deletediscon <- branch with the delete self.blahblah thing, test it, have at it, maybe I'll merge both just to make sure, with a side helping of null.

**Comment by VibroAxe** [comment]
no kill like overkill :D 

Is there a zip release of this branch and I'll get testing?

**Comment by ntoff** [comment]
yeah for zips you just go to the branch and go clone/download and click on the "download zip" thing (right click) and copy the link.

But here's that link for anyone else who may want to take a look https://github.com/ntoff/OctoPrint-Estop/archive/reconnect-deletediscon.zip

**Comment by VibroAxe** [comment]
I had not realised these were just a direct download of the repo my bad

That change certainly works and correctly deletes the event, with some of my printers i've noticed that the 3s isn't quite long enough to complete the proper shutdown/reconnect. Perhaps this would be better as a final setting "time to reconnect after" to allow people to tune?

**Comment by ntoff** [comment]
I want this plugin to be as simple as possible, as little to go wrong as possible, even having an automatic re-connect is complicating things.

An emergency shutdown / stop *should* really require manual intervention to get going again, either a manual printer reset or ideally, it'd shut off the power all together and require a person to go turn it back on again after making sure whatever caused them to press the button, was fixed. That's the entire point of an *emergency* stop.

I added the ability to change the command it sends because I know some firmware actually use a different command (see smoothieware does dumb things https://github.com/ntoff/OctoPrint-Estop/issues/2 ), if the automatic re-connect is causing this many issues, I'm not going to implement it (sorry). 

If a user is relying on the disconnect / reconnect cycle to reset and stop the printer, even 3 seconds is a long time, and seeing as most boards only reset on connect (of the boards that reset at all on serial activity), increasing that value is only going to increase the amount of time it takes to stop the printer. The user might as well just press OctoPrint's own disconnect button and then reconnect again when sufficient time has passed. I'm sorry but a lengthy delay will only make an emergency stop / reset even more useless.

As it stands, I think I'm going to file this one under "too complicated / unpredictable", as it will give people a false sense of security thinking the printer will reset, and then they go and set the timeout to 30 seconds or something. I don't want that to happen.

**Comment by ntoff** [comment]
Closing this request.

While I agree an automatic reconnect would be handy, I see 2 main reasons to not implement it:

1. It complicates the plugin code, more stuff to go wrong
2. If it's implied the plugin will disconnect and reconnect to reset the control board, and a user's control board has its reset features disabled, this could cause undesired failure if a user is relying on such a feature and believes this plugin to somehow magically be able to reset their board.

Thirdly but not really a reason, if you've hit the emergency stop then it's probably for a good reason and you're already in OctoPrint's interface anyway, so clicking on the reconnect button is at most a very slight inconvenience compared with whatever went wrong with the print that caused an emergency situation.
